# Generated by Django 5.2 on 2025-04-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_customer_id',
            new_name='stripe_id',
        ),
    ]
