# Generated by Django 5.2 on 2025-04-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscriptionprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionprice',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
